### ISSUE TITLE
Preprocess Location to Mineral pipeline

### ISSUE THREAD

**Issue by JasonLo** [UW-xDD/text2graph_llm#51]
Run extraction pipeline on CHTC

**Comment by JasonLo** [comment]
Running Location to Mineral extraction pipeline on full dataset on CHTC, ETA: June 13.

**Comment by JasonLo** [comment]
NCCL error in some jobs. Will only work on A100-80GB GPUs? (Previous batch worked with the same setup, unsure why this issue occurred.) Resubmitted with this additional restriction.

**Comment by iross** [comment]
Hmm when was the previous batch run? And what is the error? We rolled out a small config change to how docker starts up ~2 weeks ago. I'd be shocked if that was the culprit but it's a bit suspicious...

**Comment by JasonLo** [comment]
Previous run was like 6 weeks ago? roughly

**Comment by JasonLo** [comment]
The error involves the NCCL driver. It seems more related to `vllm` than CHTC, or possibly their interaction. Using NCCL with a single GPU job doesn't make sense.

**Comment by iross** [comment]
Yeah some unexpected configuration or interaction in the CHTC setting is my main concern. It doesn’t really make much sense but these kinds of things have surprised me in the past.


On Thu, Jun 13 2024 at 11:37 AM, Jason Lo ***@***.******@***.***>> wrote:

The error involves the NCCL driver. It seems more related to vllm than CHTC, or possibly their interaction. Using NCCL with a single GPU job doesn't make sense.
